// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNvWuOoJq4obWslZBKKbXtzGSh3DKRpPc',
    appId: '1:614922055253:web:256b75f1b201ca0058eedc',
    messagingSenderId: '614922055253',
    projectId: 'fluttertuga-notes',
    authDomain: 'fluttertuga-notes.firebaseapp.com',
    storageBucket: 'fluttertuga-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChp-RC6YZdNXnF7Ub16ujh9AWEUzO-smM',
    appId: '1:614922055253:android:9d94a311b4b996a758eedc',
    messagingSenderId: '614922055253',
    projectId: 'fluttertuga-notes',
    storageBucket: 'fluttertuga-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJaegOlEyHz8wNWPEFvIL_57lOhH22lCY',
    appId: '1:614922055253:ios:87db59521145c47558eedc',
    messagingSenderId: '614922055253',
    projectId: 'fluttertuga-notes',
    storageBucket: 'fluttertuga-notes.appspot.com',
    iosClientId: '614922055253-4duq7a88mu4eus2u96p475s9f5rnhoek.apps.googleusercontent.com',
    iosBundleId: 'com.batuga.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJaegOlEyHz8wNWPEFvIL_57lOhH22lCY',
    appId: '1:614922055253:ios:62536420fbfa042258eedc',
    messagingSenderId: '614922055253',
    projectId: 'fluttertuga-notes',
    storageBucket: 'fluttertuga-notes.appspot.com',
    iosClientId: '614922055253-p94oeek3jha10vj1d28g55qs33bknhd9.apps.googleusercontent.com',
    iosBundleId: 'com.batuga.notesApp.RunnerTests',
  );
}
